global:
  radarr:
    - name: radarr_1
      api: abcdefghijlmnop
      url: http://192.168.1.200:7878
    - name: radarr_2
      api: abcdefghijklmnop
      url: http://localhost:1212
  sonarr:
    - name: sonarr_1
      api: abcdefghijlmnop
      url: http://192.168.1.200:8989
    - name: sonarr_2
      api: abcdefghijlmnop
      url: http://192.168.1.200:9090

upgradinatorr:
  log_level: info
  dry_run: true
  discord_webhook:
  radarr:
    - name: radarr_1
      count:
      monitored: true
      status: released
      tag_name:
      unattended: false
    - name: radarr_2
      count:
      monitored: true
      status: released
      tag_name:
      unattended: false
  sonarr:
    - name: sonarr_1
      count:
      monitored: true
      status: released
      tag_name:
      unattended: false
    - name: sonarr_2
      count:
      monitored: true
      status: released
      tag_name:
      unattended: false
      dry_run: false

renameinator:
  log_level: info
  dry_run: true
  discord_webhook:
  radarr:
    - name: radarr_1
      count: 1
      tag_name: rename
      unattended: false
      reset: false
      dry_run: true
  sonarr:
    - name: sonarr_1
      count: 1
      tag_name: rename
      unattended: false
      reset: false
      dry_run: true
