version: "3.9"

services:
  daps:
    container_name: daps
    image: ghcr.io/drazzilb08/daps:v2.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    restart: unless-stopped