#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
------------------------------------------------
    Starting userScripts
------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/config.sample.yml" || ! $(diff /app/config/config.sample.yml "${CONFIG_DIR}/config.sample.yml") ]]; then
    echo "Config file not found or different. Copying config.sample.yml to ${CONFIG_DIR}"
    cp /app/config/config.sample.yml "${CONFIG_DIR}"
fi
if [[ ! -f "${CONFIG_DIR}/backup-appdata-example.conf" || ! $(diff /app/config/backup-appdata-example.conf "${CONFIG_DIR}/backup-appdata-example.conf") ]]; then
    echo "Backup appdata config file not found. Copying backup-appdata-example.conf to ${CONFIG_DIR}"
    cp /app/config/backup-appdata-example.conf "${CONFIG_DIR}"
fi
if [[ ! -f "${CONFIG_DIR}/backup-plex-example.conf" || ! $(diff /app/config/backup-plex-example.conf "${CONFIG_DIR}/backup-plex-example.conf") ]]; then
    echo "Backup plex config file not found. Copying backup-plex-example.conf to ${CONFIG_DIR}"
    cp /app/config/backup-plex-example.conf "${CONFIG_DIR}"
fi

echo "Setting permissions for ${CONFIG_DIR} and ${DATA_DIR} to ${PUID}:${PGID}"
chown hotio:hotio -R "${CONFIG_DIR}"
chown hotio:hotio -R "${DATA_DIR}"
chown hotio:hotio -R "${APP_DIR}"
