name: Docker Develop Release

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  docker-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub (optional)
        if: ${{ github.action == 'docker/build-push-action' }}  # Only login if triggered by docker/build-push-action
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.action != 'docker/build-push-action' }}  # Push only if not triggered by this job
          tags: ${{ secrets.DOCKER_USERNAME }}/userscripts:${{ github.sha }}  # Use commit SHA for tag

      - name: Push to ghcr.io (optional)
        if: ${{ github.action != 'docker/build-push-action' }}  # Only push to ghcr.io if not triggered by docker/build-push-action
        run: |
          docker login --username ${{ secrets.GH_USERNAME }} --password ${{ secrets.GH_TOKEN }} ghcr.io
          docker tag ${{ secrets.DOCKER_USERNAME }}/userscripts:${{ github.sha }} ghcr.io/drazzilb08/userscripts:dev
          docker push ghcr.io/drazzilb08/userscripts:dev

