name: Docker Latest Release

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/.github/**'

jobs:

  docker-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            "BRANCH=${{ vars.GITHUB_REF_NAME }}"
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/daps:latest
            ghcr.io/drazzilb08/daps:latest
