name: Delete Docker Image Tags for Deleted Branches (Except dev and master)

on:
  delete:
    branches:
      - '*'  # Triggered on branch deletion

jobs:
  docker-delete-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Get the deleted branch name
        id: get_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Check if branch is not dev or master
        id: check_branch
        run: |
          if [[ "${{ steps.get_branch.outputs.BRANCH_NAME }}" == "dev" || "${{ steps.get_branch.outputs.BRANCH_NAME }}" == "master" ]]; then
            echo "Skipping deletion for branch: ${{ steps.get_branch.outputs.BRANCH_NAME }}"
            exit 0  # Skip if the branch is dev or master
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Delete Docker tag from Docker Hub
        run: |
          docker rmi ${{ secrets.DOCKER_USERNAME }}/daps:${{ steps.get_branch.outputs.BRANCH_NAME }} || echo "Tag not found on Docker Hub"
        continue-on-error: true

      - name: Delete Docker tag from GitHub Container Registry
        run: |
          docker rmi ghcr.io/drazzilb08/daps:${{ steps.get_branch.outputs.BRANCH_NAME }} || echo "Tag not found on GitHub Container Registry"
        continue-on-error: true