name: Delete GHCR Docker Tag for Deleted Branch

on:
  delete:
    branches:
      - '*'  # Triggers on branch deletion

jobs:
  ghcr-delete-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Get the deleted branch name
        id: get_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Check if branch is not dev or master
        run: |
          if [[ "${{ steps.get_branch.outputs.BRANCH_NAME }}" == "dev" || "${{ steps.get_branch.outputs.BRANCH_NAME }}" == "master" ]]; then
            echo "Skipping deletion for branch: ${{ steps.get_branch.outputs.BRANCH_NAME }}"
            exit 0
          fi

      - name: Delete tag from GHCR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TAG_NAME: ${{ steps.get_branch.outputs.BRANCH_NAME }}
        run: |
          REPO="drazzilb08/daps"
          # Get the tag digest
          DIGEST=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            "https://ghcr.io/v2/${REPO}/manifests/${TAG_NAME}" \
            -I | grep -i 'docker-content-digest:' | awk '{print $2}' | tr -d '\r')
          if [[ -z "$DIGEST" ]]; then
            echo "Tag not found on GHCR"
            exit 0
          fi
          # Delete the tag
          curl -s -X DELETE -H "Authorization: Bearer $GH_TOKEN" \
            "https://ghcr.io/v2/${REPO}/manifests/${DIGEST}" \
            && echo "Deleted GHCR tag: ${TAG_NAME}" || echo "Failed to delete GHCR tag: ${TAG_NAME}"