name: Docker Latest Release

on:
  push:
    branches:
      - '**.patch-*' # Trigger on patch branches
  delete:
    branches:
      - '**.patch-*' # Trigger on patch branch deletion

jobs:
  docker-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Build and push Docker image (patch-* branch)
        if: startsWith(github.ref, 'refs/heads/patch-') && github.event_name == 'push'
        run: |
          docker build --build-arg BRANCH=$(git rev-parse --abbrev-ref HEAD) -t ghcr.io/${{ secrets.GH_USERNAME }}/userscripts:${{ github.ref }} .
          docker push ghcr.io/${{ secrets.GH_USERNAME }}/userscripts:${{ github.ref }}

      - name: Remove container from remote repositories (branch deletion)
        if: startsWith(github.ref, 'refs/heads/patch-') && github.event_name == 'delete'
        run: |
          docker rmi ghcr.io/${{ secrets.GH_USERNAME }}/userscripts:${{ github.ref }} || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/userscripts:${{ github.ref }} || true
