name: Docker Version Release

on:
  create:
    tags:
      - v*

jobs:

  docker-latest:
    runs-on: ubuntu-latest
  
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Build GH Container
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref }} .

      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/userscripts:${{ steps.get_version.outputs.VERSION }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG
          token: ${{ secrets.GH_PAT }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}